"""`pnk link` — the authoring command, and the only machine writer of `links[]`.

Two KBs on disk in every fixture, as `test_sync_links` builds them: the `<alias>:<path>` grammar,
the partner-id refusal and the cross-KB round trip do not exist in a single-KB fixture at all.

**The byte-level tests read `read_bytes()`, never `read_text()`.** `read_text` normalises line
endings, so a comparison built on it reports "byte-identical" about a file whose newlines changed —
the mistake L5b's own CRLF check made and had to be redone (docs/RETROSPECTIVES.md).
"""

from __future__ import annotations

import contextlib
import io
import os
from pathlib import Path
from typing import Any

import pytest
import yaml
from test_sync_links import Kb, links_in, make_kb, run

from pinakes import paths
from pinakes.cli import EXIT_FAILURE, EXIT_OK, main
from pinakes.errors import PinakesError
from pinakes.ids import mint_doc_id, mint_kb_id
from pinakes.link import add, resolve_target
from pinakes.manifest import load
from pinakes.sidecar import SIDECAR_SUFFIX, read

# --- Harness -----------------------------------------------------------------------------


def link(kb: Kb, source: str, target: str, rel: str) -> tuple[int, str]:
    """Run `pnk link` against `kb`, returning `(exit code, stdout)`."""
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        code = main(["link", source, target, "--kb", str(kb.root), "--rel", rel])
    return code, buffer.getvalue()


def handwrite(kb: Kb, name: str, body: str) -> Path:
    """Replace one sidecar with hand-written text, verbatim.

    Hand-written rather than dumped: every test below is about what survives a rewrite, and a
    fixture generated by a YAML dumper carries none of the comments, quoting or indentation that
    are the thing under test.
    """
    path = kb.sidecar(name)
    path.write_text(body, encoding="utf-8")
    return path


def commented(kb: Kb, name: str, target: str) -> str:
    """A sidecar carrying every construct this increment must not destroy: comments at the top, on
    a value, inside a sequence and on a link entry; a per-link key pinakes does not know; and the
    two YAML 1.1 traps (`NO`, `no`) that must still read back as strings."""
    return f"""\
# The keeper's own note, at the top.
id: {kb.docs[name]}
title: Alpha        # trailing, on the title
tags:
  # about the tags
- policy
- "no"
links:
- to: {target}   # why this link exists
  rel: related
  note: mine to keep
country: NO
"""


@pytest.fixture
def pair(tmp_path: Path) -> tuple[Kb, Kb]:
    """A local KB with three documents and a partner it declares as `partner`."""
    local = make_kb(tmp_path / "local", "local", ["alpha", "beta", "gamma"])
    partner = make_kb(tmp_path / "partner", "partner", ["one"])
    local.connect(partner, "partner")
    return local, partner


def links_of(kb: Kb, name: str) -> list[tuple[str, str]]:
    """The `(to, rel)` pairs a sidecar carries, as `read()` resolves them."""
    parsed = read(kb.sidecar(name), owner=kb.kb_id)
    return [(str(entry.to), entry.rel) for entry in parsed.links]


# --- The three target grammars -----------------------------------------------------------


def test_each_dst_grammar_resolves(pair: tuple[Kb, Kb]) -> None:
    """A path in this KB, a `pnk://` URI, and `<alias>:<path>` — all three, on one document."""
    local, partner = pair
    assert link(local, "docs/alpha.md", "docs/beta.md", "related")[0] == EXIT_OK
    assert link(local, "docs/alpha.md", local.uri("gamma"), "cites")[0] == EXIT_OK
    assert link(local, "docs/alpha.md", "partner:docs/one.md", "counterpart")[0] == EXIT_OK

    assert links_of(local, "alpha") == [
        (local.uri("beta"), "related"),
        (local.uri("gamma"), "cites"),
        (f"pnk://{partner.kb_id}/{partner.docs['one']}", "counterpart"),
    ]


def test_an_alias_is_resolved_to_a_ulid_on_write(pair: tuple[Kb, Kb]) -> None:
    """The alias is machine-local and never reaches disk — §2.2's single decision that makes a
    link survive being shared."""
    local, partner = pair
    assert link(local, "docs/alpha.md", "partner:docs/one.md", "counterpart")[0] == EXIT_OK

    text = local.sidecar("alpha").read_text(encoding="utf-8")
    assert "partner:" not in text
    assert f"pnk://{partner.kb_id}/{partner.docs['one']}" in text


def test_self_is_expanded_on_write(pair: tuple[Kb, Kb]) -> None:
    """`pnk://self/…` is a convenience at the argument, never a thing written down: a sidecar
    copied into another KB must keep pointing at the document it always meant."""
    local, _partner = pair
    assert link(local, "docs/alpha.md", f"pnk://self/{local.docs['beta']}", "related")[0] == EXIT_OK

    text = local.sidecar("alpha").read_text(encoding="utf-8")
    assert "self" not in text
    assert f"pnk://{local.kb_id}/{local.docs['beta']}" in text


def test_a_colon_in_a_path_that_is_not_a_declared_alias_stays_a_path(pair: tuple[Kb, Kb]) -> None:
    """The alias grammar bites **only** on a declared `[[links.kb]]` name. A POSIX path may carry a
    colon, and reading `docs/2026: review.md` as a KB named `docs/2026` would refuse a real file."""
    local, _partner = pair
    document = local.root / "docs" / "2026: review.md"
    document.write_text("# review\n", encoding="utf-8")
    doc_id = mint_doc_id()
    document.with_name(document.name + SIDECAR_SUFFIX).write_text(
        f"id: {doc_id}\n", encoding="utf-8"
    )

    assert link(local, "docs/alpha.md", "docs/2026: review.md", "cites")[0] == EXIT_OK
    assert links_of(local, "alpha") == [(f"pnk://{local.kb_id}/{doc_id}", "cites")]


def test_a_pnk_uri_wins_over_an_alias_that_happens_to_be_called_pnk(
    pair: tuple[Kb, Kb], tmp_path: Path
) -> None:
    """`pnk://…` partitions on `:` as the alias `pnk`. The prefix is tried first, so a KB someone
    aliased `pnk` cannot capture every URI in the manifest."""
    local, _partner = pair
    local.connect(make_kb(tmp_path / "third", "third", ["only"]), "pnk")
    assert link(local, "docs/alpha.md", local.uri("beta"), "related")[0] == EXIT_OK
    assert links_of(local, "alpha") == [(local.uri("beta"), "related")]


def test_a_well_formed_pnk_uri_to_an_absent_target_is_written(pair: tuple[Kb, Kb]) -> None:
    """Both ULIDs are in the URI; nothing here needs the file. Refusing would make authoring depend
    on which KBs happen to be checked out — and `tests/free_path_run.py` depends on this."""
    local, _partner = pair
    elsewhere = f"pnk://{mint_kb_id()}/{mint_doc_id()}"
    assert link(local, "docs/alpha.md", elsewhere, "cites")[0] == EXIT_OK
    assert links_of(local, "alpha") == [(elsewhere, "cites")]


# --- Refusals ----------------------------------------------------------------------------


def test_an_unresolvable_dst_is_refused_with_its_remedy(
    pair: tuple[Kb, Kb], capsys: pytest.CaptureFixture[str]
) -> None:
    local, _partner = pair
    before = local.sidecar("alpha").read_bytes()

    assert (
        main(
            ["link", "docs/alpha.md", "nope:docs/one.md", "--kb", str(local.root), "--rel", "cites"]
        )
        == EXIT_FAILURE
    )
    err = capsys.readouterr().err
    assert "nope:docs/one.md" in err
    # The remedy, not only the complaint — and it answers the question actually asked. `nope` looks
    # like an alias, so "not a document in this KB" alone would be true and unhelpful.
    assert "`nope` is not a linked KB either" in err
    assert "`partner`" in err
    assert local.sidecar("alpha").read_bytes() == before


def test_an_alias_pointing_at_a_kb_that_is_not_here_is_refused(pair: tuple[Kb, Kb]) -> None:
    """`[[links.kb]] path` resolving to nothing is a refusal at authoring time, unlike a
    `pnk://` URI: an alias cannot be turned into a ULID pair without reading that KB."""
    local, partner = pair
    for entry in partner.root.rglob("*"):
        if entry.is_file():
            entry.unlink()

    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/alpha.md", target="partner:docs/one.md", rel="cites")
    # The *alias*, not a bare `"partner" in message` — the tmp_path in that message ends in
    # `/partner` too, so the loose form was satisfied by the path and would survive the alias being
    # dropped from the wording entirely.
    assert caught.value.message.startswith("linked KB `partner` ")


def test_an_alias_naming_no_document_says_so(pair: tuple[Kb, Kb]) -> None:
    """`partner:` with nothing after it. Without this refusal it falls through to "'' is not a
    document in `partner`", which describes the empty string rather than the mistake."""
    local, _partner = pair
    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/alpha.md", target="partner:", rel="cites")
    assert "names no document" in caught.value.message
    assert "partner:docs/" in caught.value.remedy


def test_a_kb_declaring_no_linked_kbs_says_that_rather_than_listing_none(
    pair: tuple[Kb, Kb],
) -> None:
    """The other branch of the same remedy. With no `[[links.kb]]` at all, "this manifest declares
    " followed by nothing is a sentence that stops mid-thought."""
    local, _partner = pair
    local.disconnect_all()
    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/alpha.md", target="partner:docs/one.md", rel="cites")
    assert "declares no `[[links.kb]]` at all" in caught.value.remedy


def test_a_partner_kb_that_cannot_be_read_is_unreachable_not_a_traceback(
    pair: tuple[Kb, Kb], monkeypatch: pytest.MonkeyPatch
) -> None:
    """A partner directory this user cannot read raised `PermissionError` out of `cli.main`.

    The third instance of one class in one increment: `expanduser()`'s `RuntimeError`, `is_file()`'s
    `EACCES` on the source path, and this. Twice the fix closed the instance in front of it and
    left the rest — a defect class is not closed until it has been searched for.
    """
    local, partner = pair
    # **Injected at `os.stat`, the OS boundary, and it used to be injected at `Path.is_file`.**
    # That was the spelling the production probe happened to use, and it stopped intercepting the
    # moment the probe became version-independent — the same seam failure this file already
    # records one test above. Worse, it had gone blind before it went red: on 3.14 the real
    # `Path.is_file()` returns `False` for an unreadable directory instead of raising, so the
    # guard under test was dead there while the fake entered it and this passed on both.
    # `test_a_partner_kb_present_but_unreadable_is_not_reported_as_absent` is the non-injecting
    # half; this one earns its place by running as root, where the `chmod` fixture is skipped.
    real_stat = os.stat

    def denied(target: Any, *args: Any, **kwargs: Any) -> os.stat_result:
        if isinstance(target, str | Path) and str(target).startswith(str(partner.root)):
            raise PermissionError(13, "Permission denied")
        return real_stat(target, *args, **kwargs)

    monkeypatch.setattr(os, "stat", denied)
    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/alpha.md", target="partner:docs/one.md", rel="cites")
    monkeypatch.undo()

    assert caught.value.message.startswith("linked KB `partner` ")
    # The errno text, not just the class. Asserting only the prefix left the `strerror` extraction
    # unpinned — blanking the reason kept all 42 tests green.
    assert "Permission denied" in caught.value.message


@pytest.mark.skipif(
    os.geteuid() == 0, reason="root traverses a 0o000 directory, so the state cannot be built"
)
def test_a_partner_kb_present_but_unreadable_is_not_reported_as_absent(
    pair: tuple[Kb, Kb], tmp_path: Path
) -> None:
    """The non-injecting half, and the one that would have caught the 3.14 regression.

    A partner KB behind a directory this process may not traverse is *present*. Every filesystem
    predicate answers `False` for it — the same `False` they give for a path that is not there — so
    on 3.14 `pnk link` told the user the partner did not exist, with the directory on disk.

    **Two shapes, because they enter `why_not_a_kb` at different points.** `walled` is refused at
    the partner root itself; `partner` is a readable directory whose `pinakes.toml` cannot be
    reached. Both must name the permission, and neither may say "no such directory".
    """
    local, partner = pair
    walled = make_kb(tmp_path / "walled" / "kb", "walled", ["w"])
    local.connect(walled, "walled")

    os.chmod(tmp_path / "walled", 0o000)
    os.chmod(partner.root, 0o000)
    try:
        with pytest.raises(PinakesError) as root_refused:
            add(load(local.root), source="docs/alpha.md", target="walled:docs/w.md", rel="cites")
        with pytest.raises(PinakesError) as manifest_refused:
            add(load(local.root), source="docs/alpha.md", target="partner:docs/one.md", rel="cites")
    finally:
        os.chmod(tmp_path / "walled", 0o755)
        os.chmod(partner.root, 0o755)

    for caught, alias in ((root_refused, "walled"), (manifest_refused, "partner")):
        message = caught.value.message
        assert message.startswith(f"linked KB `{alias}` "), message
        assert "Permission denied" in message, message
        assert "no such directory" not in message, (
            f"{alias} is present and merely unreadable, and must not be reported as absent"
        )

    # Control: with the permissions restored and nothing else changed, the same call goes through.
    add(load(local.root), source="docs/alpha.md", target="partner:docs/one.md", rel="cites")


def test_a_linked_kb_path_that_will_not_expand_is_unreachable_not_a_traceback(
    pair: tuple[Kb, Kb],
) -> None:
    """`[[links.kb]] path` may be `~/kbs/partner`, so `resolve_path` calls `expanduser()` — which
    raises `RuntimeError` on an unknown user. It sat one line *above* the try that had just been
    added for exactly this class, which is how it survived four rounds of fixing that class."""
    local, _partner = pair
    manifest = local.root / "pinakes.toml"
    text = manifest.read_text(encoding="utf-8")
    manifest.write_text(
        text.replace(f'path = "{_declared_path(text)}"', 'path = "~nosuchuser12345/kb"'),
        encoding="utf-8",
    )

    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/alpha.md", target="partner:docs/one.md", rel="cites")
    assert caught.value.message.startswith("linked KB `partner` ")
    # **The path it names is the one the user wrote.** Asserting only the prefix let an earlier
    # version report the *local KB root* — a real, readable directory with nothing to do with the
    # failure — while the string they typed appeared nowhere.
    assert "~nosuchuser12345/kb" in caught.value.message
    assert str(local.root) not in caught.value.message
    # And exactly one full stop: this reason is borrowed from `RuntimeError`, which ends in one.
    assert not caught.value.message.endswith("..")


def test_an_unresolvable_linked_kb_path_is_never_resolved_through_the_working_directory(
    pair: tuple[Kb, Kb], tmp_path: Path
) -> None:
    """The `pnk link` half of review 8's finding — **a misleading refusal, not a bad write.**

    Review 7 made `resolve_path` answer the declared text when it cannot resolve. That text is
    *relative*, and `_via_alias` used it as the base it read the partner's `pinakes.toml` and
    documents from, so with a directory of that literal name in the working directory the walk
    re-anchored on the CWD and genuinely read the **decoy's** manifest.

    **It stopped there**, and review 8's own account of this was wrong — corrected in review 9,
    which reproduced it. `_document_in` compares an absolute `joined.parent.resolve()` against the
    *relative* `root`, which can never be `is_relative_to`, so the refusal fires before any sidecar
    is read: `'docs/one.md' is outside \\`partner\\`` — telling the user the path they typed
    correctly is wrong, and naming neither the KB path nor the expansion failure that is the actual
    fault. The severe outcome (a permanent ULID from the wrong KB) was asserted, not measured; the
    row-deleting `pnk sync` half of the same finding is the one that is real.

    The first assertion is therefore what discriminates. The two below it are defence in depth
    against a future change that makes the decoy reachable — they were never reached under the
    round-7 mutation, which is exactly how the overstatement survived a round.

    The decoy carries the partner's own `[kb] id`, so the id-mismatch refusal cannot be what
    catches it, and a `docs/one.md` whose ULID differs from the real partner's, so the wrong answer
    is distinguishable from the right one.
    """
    local, partner = pair
    manifest = local.root / "pinakes.toml"
    text = manifest.read_text(encoding="utf-8")
    manifest.write_text(
        text.replace(f'path = "{_declared_path(text)}"', 'path = "~nosuchuser12345/kb"'),
        encoding="utf-8",
    )

    workdir = tmp_path / "workdir"
    workdir.mkdir()
    decoy = make_kb(workdir / "~nosuchuser12345" / "kb", "decoy", ["one"], kb_id=str(partner.kb_id))
    assert decoy.docs["one"] != partner.docs["one"]

    here = os.getcwd()
    os.chdir(workdir)
    try:
        with pytest.raises(PinakesError) as caught:
            add(load(local.root), source="docs/alpha.md", target="partner:docs/one.md", rel="cites")
    finally:
        os.chdir(here)

    assert "~nosuchuser12345/kb" in caught.value.message
    assert str(decoy.docs["one"]) not in caught.value.message
    assert read(local.sidecar("alpha"), owner=local.kb_id).links == ()


def _declared_path(manifest_text: str) -> str:
    """The `[[links.kb]] path` value, read back rather than assumed — `make_kb` computes it with
    `os.path.relpath`, so hard-coding it here would break the day the fixture layout moves."""
    for line in manifest_text.splitlines():
        if line.startswith("path = "):
            return line.split('"')[1]
    raise AssertionError("the fixture manifest declares no [[links.kb]] path")


def test_a_linked_kb_path_naming_a_regular_file_says_so(
    pair: tuple[Kb, Kb], tmp_path: Path
) -> None:
    """Three cases, not two: an `is_dir()` split called an existing regular file "no such
    directory", which is the one answer a person would check and find false."""
    local, _partner = pair
    decoy = tmp_path / "decoy"
    decoy.write_text("not a KB\n", encoding="utf-8")
    manifest = local.root / "pinakes.toml"
    text = manifest.read_text(encoding="utf-8")
    manifest.write_text(
        text.replace(f'path = "{_declared_path(text)}"', f'path = "{decoy}"'), encoding="utf-8"
    )

    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/alpha.md", target="partner:docs/one.md", rel="cites")
    assert "not a directory" in caught.value.message


@pytest.mark.parametrize(
    ("shape", "expected"),
    [("directory", "not a regular file"), ("broken symlink", "broken symlink")],
)
def test_a_pinakes_toml_that_is_not_a_regular_file_says_which(
    pair: tuple[Kb, Kb], tmp_path: Path, shape: str, expected: str
) -> None:
    """The same defect as the test above, one level down — and the three-way split had it too.

    The caller's probe is `is_file()`, so a `pinakes.toml` that exists but is a *directory*, or is
    a symlink to nothing, fell through to "no pinakes.toml there" — with the file plainly visible
    in `ls`. That is the answer the docstring justifying the split calls the one a person would
    check and find false, reproduced by the code beneath it.
    """
    local, _partner = pair
    kb = tmp_path / "decoy"
    kb.mkdir()
    if shape == "directory":
        (kb / "pinakes.toml").mkdir()
    else:
        (kb / "pinakes.toml").symlink_to(tmp_path / "nothing-here")

    manifest = local.root / "pinakes.toml"
    text = manifest.read_text(encoding="utf-8")
    manifest.write_text(
        text.replace(f'path = "{_declared_path(text)}"', f'path = "{kb}"'), encoding="utf-8"
    )

    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/alpha.md", target="partner:docs/one.md", rel="cites")
    assert expected in caught.value.message
    assert "no pinakes.toml there" not in caught.value.message


def test_a_partner_with_a_malformed_kb_id_names_the_kb_it_came_from(pair: tuple[Kb, Kb]) -> None:
    """`partner_sources` raises `InvalidIdError` — a `PinakesError`, so no traceback, but on its own
    it says only that some string is not a ULID, naming neither the KB nor the file. `scan_one`
    already caught `PinakesError` for this reason; this branch did not."""
    local, partner = pair
    manifest = partner.root / "pinakes.toml"
    manifest.write_text(
        manifest.read_text(encoding="utf-8").replace(str(partner.kb_id), "not-a-ulid"),
        encoding="utf-8",
    )

    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/alpha.md", target="partner:docs/one.md", rel="cites")
    assert caught.value.message.startswith("linked KB `partner` ")
    assert "not-a-ulid" in caught.value.message
    # This reason is another `PinakesError`'s message, which already ends in a full stop.
    assert not caught.value.message.endswith("..")


def test_an_alias_whose_partner_declares_a_different_id_is_refused(pair: tuple[Kb, Kb]) -> None:
    """The partner's own `[kb] id` decides, and a disagreement is refused rather than resolved —
    `linkscan`'s rule 1, and sharper here: what gets written is permanent."""
    local, partner = pair
    text = (partner.root / "pinakes.toml").read_text(encoding="utf-8")
    (partner.root / "pinakes.toml").write_text(
        text.replace(str(partner.kb_id), str(mint_kb_id())), encoding="utf-8"
    )

    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/alpha.md", target="partner:docs/one.md", rel="cites")
    assert "is declared as" in caught.value.message


def test_a_source_with_no_sidecar_is_refused_and_none_is_minted(pair: tuple[Kb, Kb]) -> None:
    """Never mint here: a fresh ULID laid over a file that already holds a permanent one is the
    unrecoverable case, and `pnk link` has no reason to be near it."""
    local, _partner = pair
    (local.root / "docs" / "fresh.md").write_text("# fresh\n", encoding="utf-8")

    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/fresh.md", target="docs/beta.md", rel="cites")
    assert "no sidecar" in caught.value.message
    assert "pnk sync" in caught.value.remedy
    assert not (local.root / "docs" / f"fresh.md{SIDECAR_SUFFIX}").exists()


def test_an_unreadable_source_sidecar_is_never_overwritten(pair: tuple[Kb, Kb]) -> None:
    local, _partner = pair
    broken = "id: [not, a, ulid\n"
    local.sidecar("alpha").write_text(broken, encoding="utf-8")

    with pytest.raises(PinakesError):
        add(load(local.root), source="docs/alpha.md", target="docs/beta.md", rel="cites")
    assert local.sidecar("alpha").read_text(encoding="utf-8") == broken


def test_a_source_outside_the_kb_is_refused(pair: tuple[Kb, Kb], tmp_path: Path) -> None:
    """Named `elsewhere.md`, deliberately: the first version of this called it `outside.md` and
    asserted `"outside" in message`, which the interpolated *path* satisfied on its own — the
    reason could have vanished from the wording with the test still green."""
    local, _partner = pair
    elsewhere = tmp_path / "elsewhere.md"
    elsewhere.write_text("# elsewhere\n", encoding="utf-8")
    elsewhere.with_name(f"elsewhere.md{SIDECAR_SUFFIX}").write_text(
        f"id: {mint_doc_id()}\n", encoding="utf-8"
    )

    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source=str(elsewhere), target="docs/beta.md", rel="cites")
    assert "is outside this KB" in caught.value.message


def test_a_dot_dot_escape_is_still_refused(pair: tuple[Kb, Kb]) -> None:
    """The escape the containment check exists for, and the one a looser check stops catching."""
    local, _partner = pair
    with pytest.raises(PinakesError) as caught:
        add(
            load(local.root),
            source="docs/../../partner/docs/one.md",
            target="docs/beta.md",
            rel="cites",
        )
    assert "is outside this KB" in caught.value.message


def test_a_symlinked_directory_cannot_carry_a_link_out_of_the_kb(
    pair: tuple[Kb, Kb], tmp_path: Path
) -> None:
    """The regression a purely lexical check introduced, in both directions.

    `os.path.normpath` collapses `..` but follows nothing, so `docs/ext/` symlinked outside passed
    containment — and the write went out of the KB through it. In the other direction it minted a
    **permanent** `pnk://` to a ULID this KB will never index, because `Path.glob` does not recurse
    a symlinked directory, so `pnk sync` never sees the document at all.
    """
    local, _partner = pair
    outside = tmp_path / "outside"
    (outside).mkdir()
    (outside / "notes.md").write_text("# notes\n", encoding="utf-8")
    (outside / f"notes.md{SIDECAR_SUFFIX}").write_text(f"id: {mint_doc_id()}\n", encoding="utf-8")
    (local.root / "docs" / "ext").symlink_to(outside)

    for source, target in (
        ("docs/ext/notes.md", "docs/beta.md"),  # writing a sidecar outside the KB
        ("docs/alpha.md", "docs/ext/notes.md"),  # linking a ULID the KB will never hold
    ):
        with pytest.raises(PinakesError) as caught:
            add(load(local.root), source=source, target=target, rel="cites")
        assert "is outside this KB" in caught.value.message
    assert links_of(local, "alpha") == []


def test_an_unreadable_directory_is_refused_rather_than_crashing(
    pair: tuple[Kb, Kb], monkeypatch: pytest.MonkeyPatch
) -> None:
    """The unit-level pin on the clause: a refusal from the syscall becomes a `PinakesError`.

    **The fake is at `os.stat`, which is the OS boundary, and that placement is the point.** It
    used to fake `Path.is_file` — the spelling the production code happened to use — and when the
    fix moved to `paths.unreachable_through_links` the fake stopped intercepting anything and this
    test went red. That is the good outcome of a bad seam: a fake pinned to an implementation
    detail either breaks loudly when the detail moves, or, if the detail keeps its name and changes
    its *behaviour*, goes silently blind. This one did the second thing first. On 3.14
    `Path.is_file()` swallows `EACCES` and `ENAMETOOLONG`, so the `except OSError` clause under
    test was dead there — and because the fake raised on command, the clause was entered anyway and
    this test passed on both interpreters while the production branch was unreachable on one.

    **So it no longer certifies the platform, and it is not asked to.**
    `test_a_document_the_process_cannot_reach_is_refused_with_the_read_error` is the non-injecting
    half, built from a real `chmod`, and that is the test that answers "does the real call still
    refuse?". This one earns its place on the other two: it reaches `ENAMETOOLONG`, which no
    `chmod` fixture can produce, and it runs as root, where the `chmod` fixture is skipped.
    """
    local, _partner = pair
    locked = local.root / "docs" / "locked"
    locked.mkdir()
    real_stat = os.stat

    def refuse(target: Any, *args: Any, **kwargs: Any) -> os.stat_result:
        """Refuse only the paths under test — every other `stat` in the call must still work."""
        if isinstance(target, str | Path) and str(target).startswith(str(locked)):
            raise PermissionError(13, "Permission denied")
        return real_stat(target, *args, **kwargs)

    monkeypatch.setattr(os, "stat", refuse)
    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/locked/x.md", target="docs/beta.md", rel="cites")
    monkeypatch.undo()
    assert "cannot be read" in caught.value.message
    assert "Permission denied" in caught.value.message, (
        "the errno reaches the user: 'cannot be read' alone does not say what to fix"
    )

    # The other errno in the same class, and the reason this test survives the real-`chmod` one:
    # `ENAMETOOLONG` is a property of the filesystem, not of a mode bit, so no permission fixture
    # can produce it. **It was once built from a real 300-character name and converted to injection
    # after a fixture bug** — on CI the long name simply was not a document, so the test asserted
    # the wrong message rather than exercising the guard. Injection is right for *this* errno and
    # was wrong for the permission one; the two were converted together, which is how the
    # permission half went blind.
    too_long = local.root / "docs" / ("n" * 300)

    def name_too_long(target: Any, *args: Any, **kwargs: Any) -> os.stat_result:
        if isinstance(target, str | Path) and str(target).startswith(str(too_long)):
            raise OSError(63, "File name too long")
        return real_stat(target, *args, **kwargs)

    monkeypatch.setattr(os, "stat", name_too_long)
    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source=f"docs/{'n' * 300}", target="docs/beta.md", rel="cites")
    monkeypatch.undo()
    assert "cannot be read" in caught.value.message
    assert "File name too long" in caught.value.message


def test_a_refusal_that_clears_between_the_two_stats_is_still_refused(
    pair: tuple[Kb, Kb], monkeypatch: pytest.MonkeyPatch
) -> None:
    """The one branch a real fixture cannot reach: the predicate refuses, the follow-up `stat`
    succeeds.

    `_is_file` asks `unreachable_through_links` and then `stat`s a second time, purely to put the
    errno in the message — "Permission denied" is worth more than "cannot be read". Between those
    two calls the permission can change, and then there is no `OSError` to name. The refusal must
    stand anyway: the decision was taken on the first answer, and quietly proceeding because the
    second disagreed would make `pnk link` behave differently depending on how a race landed.

    **Injected deliberately, and this is the case the rule is for** — a race between two syscalls
    cannot be built from a `chmod` fixture, and what is under test is this function's own control
    flow rather than what the OS answers. The real-filesystem behaviour is covered by
    `test_a_document_the_process_cannot_reach_is_refused_with_the_read_error`.
    """
    local, _partner = pair

    def always_refused(_path: Path) -> bool:
        return True

    monkeypatch.setattr(paths, "unreachable_through_links", always_refused)
    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/alpha.md", target="docs/beta.md", rel="cites")
    monkeypatch.undo()

    assert "cannot be read" in caught.value.message
    assert caught.value.remedy is not None and "permissions" in caught.value.remedy
    assert add(load(local.root), source="docs/alpha.md", target="docs/beta.md", rel="cites"), (
        "control: the same call succeeds once the predicate is telling the truth again"
    )


def test_a_path_with_an_embedded_nul_is_refused_rather_than_crashing(pair: tuple[Kb, Kb]) -> None:
    """`Path.resolve()` raises `ValueError` — not an `OSError`, and not a `PinakesError` — on an
    embedded NUL. Unreachable through `argv`, which cannot carry one, but `add()` is a library
    entry point and `linkscan` reaches the same class from a manifest, so the guard is real.
    Untested when written: the mutation that removes it was caught by nothing.

    **The NUL has to be in a directory component**, because only the parent is resolved. A first
    version of this test put it in the filename, where `parent.resolve()` never sees it and the
    path falls through to an ordinary "not a document" refusal — a test for a guard, written with
    an input that does not reach the guard.
    """
    local, _partner = pair
    for source, target in (
        ("docs/a\x00b/x.md", "docs/beta.md"),
        ("docs/alpha.md", "docs/a\x00b/x.md"),
        # **The filename case, which the paragraph above says falls through — it no longer does.**
        # It was a graceful "is not a document in this KB" only because `Path.is_file()` answered
        # `False` for a NUL. The permission fix replaced that call with `os.stat`, which raises
        # `ValueError` — not an `OSError`, so it escaped `_is_file`'s guard entirely and reached
        # `cli.main` as a traceback. Caught by an adversarial pass over that fix, with `main` as
        # the control; it is here so the fall-through can never silently become a crash again.
        ("docs/bad\x00name.md", "docs/beta.md"),
        ("docs/alpha.md", "docs/bad\x00name.md"),
    ):
        with pytest.raises(PinakesError) as caught:
            add(load(local.root), source=source, target=target, rel="cites")
        assert "not a usable path" in caught.value.message


def test_a_document_inside_the_root_but_outside_sources_can_be_linked(
    pair: tuple[Kb, Kb],
) -> None:
    """The stated residual, pinned so it is a decision rather than an accident.

    The boundary is the KB **root**, as the plan specifies; `[sources]` membership depends on the
    `include`/`exclude` globs as well as `roots`, so answering it here means re-implementing
    `walk_sources` and refusing a "link it now, ingest it next" order of work. The link simply does
    not resolve until the document is ingested, which `pnk links` already reports honestly.
    """
    local, _partner = pair
    staging = local.root / "staging"
    staging.mkdir()
    (staging / "notes.md").write_text("# notes\n", encoding="utf-8")
    doc_id = mint_doc_id()
    (staging / f"notes.md{SIDECAR_SUFFIX}").write_text(f"id: {doc_id}\n", encoding="utf-8")

    assert link(local, "docs/alpha.md", "staging/notes.md", "cites")[0] == EXIT_OK
    assert links_of(local, "alpha") == [(f"pnk://{local.kb_id}/{doc_id}", "cites")]


def test_an_absolute_source_behind_a_symlinked_ancestor_is_accepted(
    pair: tuple[Kb, Kb], tmp_path: Path
) -> None:
    """`manifest.load` resolves the KB root, so comparing an unresolved path against it could never
    match — and this is the *ordinary* shape: macOS `/tmp` is a symlink to `/private/tmp`, and any
    checkout behind a symlink produces it from shell completion and `$PWD` alike. The user names the
    KB by that very path and was told the document inside it was outside it."""
    local, _partner = pair
    alias = tmp_path / "via-symlink"
    alias.symlink_to(local.root)

    assert link(local, str(alias / "docs" / "alpha.md"), "docs/beta.md", "cites")[0] == EXIT_OK
    assert links_of(local, "alpha") == [(local.uri("beta"), "cites")]


def test_a_symlinked_document_inside_the_kb_can_be_linked(
    pair: tuple[Kb, Kb], tmp_path: Path
) -> None:
    """`pnk sync` indexes it, `pnk doctor` calls its sidecar readable and `pnk links` traverses it —
    so refusing it here made a document that this KB demonstrably contains impossible to link, in
    either direction, with a remedy that repeated the path the user had typed correctly.

    Refused because `resolve()` followed the final symlink *before* asking whether the result was
    inside the KB. Membership is decided by the path under `[sources]`, and `Path.glob` does yield
    a symlinked **file** — unlike a symlinked directory, which the test above keeps refused.
    """
    local, _partner = pair
    real = tmp_path / "kept-elsewhere.md"
    real.write_text("# kept elsewhere\n", encoding="utf-8")
    (local.root / "docs" / "linked.md").symlink_to(real)
    doc_id = mint_doc_id()
    (local.root / "docs" / f"linked.md{SIDECAR_SUFFIX}").write_text(
        f"id: {doc_id}\n", encoding="utf-8"
    )

    assert link(local, "docs/linked.md", "docs/beta.md", "cites")[0] == EXIT_OK
    assert links_of(local, "linked") == [(local.uri("beta"), "cites")]
    # ...and as a target, which is the other half of "in either direction".
    assert link(local, "docs/alpha.md", "docs/linked.md", "cites")[0] == EXIT_OK
    assert links_of(local, "alpha") == [(f"pnk://{local.kb_id}/{doc_id}", "cites")]


def test_a_home_relative_path_is_refused_rather_than_crashing(pair: tuple[Kb, Kb]) -> None:
    """`Path.expanduser()` raises `RuntimeError` on an unknown user, which is not a `PinakesError`
    and left `cli.main` printing a traceback. It bought nothing: this argument is KB-root-relative,
    so anything a `~` expanded to was refused by the containment check on the next line anyway."""
    local, _partner = pair
    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="~nosuchuser1234/x.md", target="docs/beta.md", rel="cites")
    assert "is not a document in this KB" in caught.value.message


def test_a_sidecar_named_as_the_source_is_refused(pair: tuple[Kb, Kb]) -> None:
    """Tab completion offers the sidecar as readily as the document, and `write()` would otherwise
    be handed a sidecar for a file that is itself one."""
    local, _partner = pair
    with pytest.raises(PinakesError) as caught:
        add(
            load(local.root),
            source=f"docs/alpha.md{SIDECAR_SUFFIX}",
            target="docs/beta.md",
            rel="cites",
        )
    assert "is a sidecar" in caught.value.message
    assert "alpha.md" in caught.value.remedy


def test_an_empty_rel_is_refused_before_anything_is_read(pair: tuple[Kb, Kb]) -> None:
    """`sidecar._links` refuses a blank `rel` at read time, which would surface as a
    corrupted-file error on a file this command had just written."""
    local, _partner = pair
    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/alpha.md", target="docs/beta.md", rel="   ")
    assert "--rel" in caught.value.message


def test_a_missing_rel_is_a_usage_error(pair: tuple[Kb, Kb]) -> None:
    local, _partner = pair
    with pytest.raises(SystemExit) as caught:
        main(["link", "docs/alpha.md", "docs/beta.md", "--kb", str(local.root)])
    assert caught.value.code == 2


# --- What the write does, and does not, touch --------------------------------------------


def test_comments_survive_a_rewrite_through_pnk_link(pair: tuple[Kb, Kb]) -> None:
    """Passing, not xfail: L5b delivered the round-trip writer, and this is the regression guard."""
    local, _partner = pair
    handwrite(local, "alpha", commented(local, "alpha", local.uri("gamma")))
    assert link(local, "docs/alpha.md", "docs/beta.md", "cites")[0] == EXIT_OK

    text = local.sidecar("alpha").read_text(encoding="utf-8")
    assert "# The keeper's own note, at the top." in text
    assert "# trailing, on the title" in text
    assert "# about the tags" in text
    assert "# why this link exists" in text
    # And the YAML 1.1 traps the parser change was made for are still strings on disk.
    assert "country: NO" in text
    assert '- "no"' in text


def test_unknown_keys_inside_a_link_entry_survive_through_pnk_link(pair: tuple[Kb, Kb]) -> None:
    """`Link` carries `to` and `rel` alone, so a merge that deleted what it does not know would
    take the user's own per-entry key with it. L6's job is not to break this."""
    local, _partner = pair
    handwrite(local, "alpha", commented(local, "alpha", local.uri("gamma")))
    assert link(local, "docs/alpha.md", "docs/beta.md", "cites")[0] == EXIT_OK

    entries = yaml.safe_load(local.sidecar("alpha").read_text(encoding="utf-8"))["links"]
    assert entries[0]["note"] == "mine to keep"
    assert len(entries) == 2


def test_an_empty_tags_or_provenance_is_not_normalised_by_adding_a_link(
    pair: tuple[Kb, Kb],
) -> None:
    """A discriminating fixture for the test below, which its own could not be.

    `tags:` and `provenance:` with nothing under them were rewritten to `tags: []` and
    `provenance: {}` on every `pnk link` — two lines changed *outside* the `links` block, in the
    increment whose test says none are. The fixture that missed it used a **populated** `tags:`
    list, which `write()` short-circuits as unchanged and so never touches: representative of a
    sidecar, not discriminating for this. Before L6 the path was unreachable outside a paid PDF
    extraction; `pnk link` reaches it on a first link, which is the common case.
    """
    local, _partner = pair
    path = handwrite(
        local, "alpha", f"id: {local.docs['alpha']}\ntitle: Alpha\ntags:\nprovenance:\n"
    )
    assert link(local, "docs/alpha.md", "docs/beta.md", "cites")[0] == EXIT_OK

    text = path.read_text(encoding="utf-8")
    assert "tags: []" not in text
    assert "provenance: {}" not in text
    assert _outside_links(text) == [
        "id: " + str(local.docs["alpha"]),
        "title: Alpha",
        "tags:",
        "provenance:",
    ]


def test_no_line_outside_the_links_block_changes_when_a_link_is_added(pair: tuple[Kb, Kb]) -> None:
    """Deliberately **not** "byte-identical": appending to an indented `links:` block re-indents
    every line of it (the next test pins that), and this fixture uses a 0-indent sequence so the
    claim in the name is the claim being made."""
    local, _partner = pair
    path = handwrite(local, "alpha", commented(local, "alpha", local.uri("gamma")))
    before = path.read_text(encoding="utf-8")
    assert link(local, "docs/alpha.md", "docs/beta.md", "cites")[0] == EXIT_OK
    after = path.read_text(encoding="utf-8")

    assert _outside_links(after) == _outside_links(before)
    assert after != before  # the block itself did change — otherwise this proves nothing


def _outside_links(text: str) -> list[str]:
    """Every line not belonging to the `links:` block, which runs to the next top-level key."""
    kept: list[str] = []
    inside = False
    for line in text.splitlines():
        if line.startswith("links:"):
            inside = True
            continue
        if inside and line[:1] not in ("", " ", "-", "#"):
            inside = False
        if not inside:
            kept.append(line)
    return kept


def test_an_indented_links_block_is_reindented_when_a_link_is_added(pair: tuple[Kb, Kb]) -> None:
    """A pinned exclusion, not a defect to fix: ruamel's dumper decides block-sequence indentation
    from its own settings, never from the source. Stated in DESIGN §2.2 and in the
    docs/INVARIANTS.md bound, and asserted here so the library moving under it is noticed."""
    local, _partner = pair
    path = handwrite(
        local,
        "alpha",
        f"id: {local.docs['alpha']}\nlinks:\n  - to: {local.uri('gamma')}\n    rel: related\n",
    )
    assert "  - to:" in path.read_text(encoding="utf-8")

    assert link(local, "docs/alpha.md", "docs/beta.md", "cites")[0] == EXIT_OK
    text = path.read_text(encoding="utf-8")
    assert "  - to:" not in text
    assert "- to:" in text
    assert len(yaml.safe_load(text)["links"]) == 2


def test_a_document_trailing_comment_is_captured_when_the_first_link_is_appended(
    pair: tuple[Kb, Kb],
) -> None:
    """The other pinned limitation, and the one `pnk link` reaches on almost every first use: a
    comment at the foot of the file is bound to the preceding construct, so appending `links:`
    after it makes it read as the block's introduction."""
    local, _partner = pair
    path = handwrite(
        local,
        "alpha",
        f"id: {local.docs['alpha']}\ntitle: Alpha\n# a note at the foot of the file\n",
    )

    assert link(local, "docs/alpha.md", "docs/beta.md", "cites")[0] == EXIT_OK
    lines = path.read_text(encoding="utf-8").splitlines()
    assert "# a note at the foot of the file" in lines
    assert lines.index("# a note at the foot of the file") < lines.index("links:")


def test_a_first_link_into_a_null_links_value_does_not_crash(pair: tuple[Kb, Kb]) -> None:
    """`links:` with nothing under it is what a user has before their first link, and it read fine
    while crashing `write()` with an unhandled `TypeError` until L5b."""
    local, _partner = pair
    handwrite(local, "alpha", f"id: {local.docs['alpha']}\nlinks:\n")

    assert link(local, "docs/alpha.md", "docs/beta.md", "cites")[0] == EXIT_OK
    assert links_of(local, "alpha") == [(local.uri("beta"), "cites")]


def test_a_rel_that_looks_like_a_boolean_is_quoted(pair: tuple[Kb, Kb]) -> None:
    """Decision 23. `rel: no` is the string `no` under YAML 1.2 and `False` under 1.1 — and the
    file is read by other people's tools too. Both write paths quote it; this is the merge one,
    which appends into an existing `links:` block."""
    local, _partner = pair
    handwrite(
        local,
        "alpha",
        f"id: {local.docs['alpha']}\nlinks:\n- to: {local.uri('gamma')}\n  rel: related\n",
    )
    assert link(local, "docs/alpha.md", "docs/beta.md", "no")[0] == EXIT_OK

    text = local.sidecar("alpha").read_text(encoding="utf-8")
    assert "rel: 'no'" in text
    # `yaml.safe_load` is YAML 1.1 — the reader this quoting exists for.
    assert yaml.safe_load(text)["links"][1]["rel"] == "no"


def test_a_rel_that_looks_like_a_boolean_is_quoted_on_a_first_link_too(pair: tuple[Kb, Kb]) -> None:
    """The other write path — `links` appearing for the first time — which took a different branch
    and did not quote until L5b's own review."""
    local, _partner = pair
    assert link(local, "docs/alpha.md", "docs/beta.md", "no")[0] == EXIT_OK
    assert yaml.safe_load(local.sidecar("alpha").read_text(encoding="utf-8"))["links"][0][
        "rel"
    ] == ("no")


def test_a_symlinked_sidecar_is_written_through_not_replaced(
    pair: tuple[Kb, Kb], tmp_path: Path
) -> None:
    """`os.replace` onto a symlink destroys the link and leaves a regular file, with the real
    sidecar untouched elsewhere still holding the old text. `create()` refuses that case outright;
    a rewrite has no reason to and simply follows it. `pnk link` is the first command a person
    points at a file of their own choosing, so it is the first to reach this routinely."""
    local, _partner = pair
    real = tmp_path / "kept-elsewhere.pnk.yaml"
    real.write_text(f"id: {local.docs['alpha']}\n", encoding="utf-8")
    local.sidecar("alpha").unlink()
    local.sidecar("alpha").symlink_to(real)

    assert link(local, "docs/alpha.md", "docs/beta.md", "cites")[0] == EXIT_OK
    assert local.sidecar("alpha").is_symlink()
    assert "rel: cites" in real.read_text(encoding="utf-8")


def test_the_source_document_is_byte_identical_afterwards(pair: tuple[Kb, Kb]) -> None:
    """`docs/` belongs to the user. The sidecar is the one file this command may write."""
    local, _partner = pair
    document = local.root / "docs" / "alpha.md"
    before = document.read_bytes()

    assert link(local, "docs/alpha.md", "docs/beta.md", "cites")[0] == EXIT_OK
    assert document.read_bytes() == before


def test_the_write_is_atomic_under_an_interrupted_rename(
    pair: tuple[Kb, Kb], monkeypatch: pytest.MonkeyPatch
) -> None:
    """A truncated sidecar loses a permanent ULID and every inbound link with it. The rename is
    what makes that impossible — so the failure leaves the original untouched and no debris."""
    local, _partner = pair
    path = local.sidecar("alpha")
    before = path.read_bytes()

    def refuse(source: object, target: object) -> None:
        raise OSError(28, "No space left on device")

    monkeypatch.setattr(os, "replace", refuse)
    with pytest.raises(PinakesError) as caught:
        add(load(local.root), source="docs/alpha.md", target="docs/beta.md", rel="cites")

    assert "could not be written" in caught.value.message
    assert path.read_bytes() == before
    assert not path.with_name(path.name + ".new").exists()


# --- Idempotence and multiplicity ---------------------------------------------------------


def test_the_same_link_twice_writes_nothing_the_second_time(pair: tuple[Kb, Kb]) -> None:
    """An authoring command is asked the same thing twice. `_merge_links` keeps multiplicity by
    design, so appending unconditionally would leave two identical entries behind."""
    local, _partner = pair
    assert link(local, "docs/alpha.md", "docs/beta.md", "cites")[0] == EXIT_OK
    after_first = local.sidecar("alpha").read_bytes()

    code, out = link(local, "docs/alpha.md", "docs/beta.md", "cites")
    assert code == EXIT_OK
    assert "already carries" in out
    assert local.sidecar("alpha").read_bytes() == after_first


def test_a_document_cannot_link_to_itself(pair: tuple[Kb, Kb]) -> None:
    """A self-loop says nothing, and would come back as the document's own neighbour. Both ways of
    reaching it — the same path twice, and a `pnk://` URI copied out of the file being edited."""
    local, _partner = pair
    for target in ("docs/alpha.md", local.uri("alpha"), f"pnk://self/{local.docs['alpha']}"):
        with pytest.raises(PinakesError) as caught:
            add(load(local.root), source="docs/alpha.md", target=target, rel="cites")
        assert "are the same document" in caught.value.message
        # Worded for the duplicate-id case too, and pointing at the tool that finds one: only the
        # ULID is known here, so "would link to itself" told anyone who had named two different
        # files that one of them was itself.
        assert "pnk doctor" in caught.value.remedy
    assert links_of(local, "alpha") == []


def test_a_second_relation_to_the_same_target_is_a_second_entry(pair: tuple[Kb, Kb]) -> None:
    """Two documents can relate two ways, and `_merge_links`' loose match must not turn the second
    relation into an edit of the first."""
    local, _partner = pair
    assert link(local, "docs/alpha.md", "docs/beta.md", "cites")[0] == EXIT_OK
    assert link(local, "docs/alpha.md", "docs/beta.md", "supersedes")[0] == EXIT_OK

    assert links_of(local, "alpha") == [
        (local.uri("beta"), "cites"),
        (local.uri("beta"), "supersedes"),
    ]


# --- Into the index -----------------------------------------------------------------------


def test_a_link_round_trips_through_sync_into_the_links_table(pair: tuple[Kb, Kb]) -> None:
    """The whole point: what `pnk link` writes is what `pnk sync` indexes and `pnk links` walks."""
    local, partner = pair
    assert link(local, "docs/alpha.md", "docs/beta.md", "related")[0] == EXIT_OK
    assert link(local, "docs/alpha.md", "partner:docs/one.md", "counterpart")[0] == EXIT_OK
    run(local)

    assert links_in(local, origin="sidecar") == sorted(
        [
            (
                str(local.kb_id),
                str(local.docs["alpha"]),
                str(local.kb_id),
                str(local.docs["beta"]),
                "related",
            ),
            (
                str(local.kb_id),
                str(local.docs["alpha"]),
                str(partner.kb_id),
                str(partner.docs["one"]),
                "counterpart",
            ),
        ]
    )


def test_resolve_target_is_reachable_without_the_cli(pair: tuple[Kb, Kb]) -> None:
    """The grammar is a function of the manifest alone — no index, no model, no side effect."""
    local, partner = pair
    manifest = load(local.root)
    assert str(resolve_target(manifest, "partner:docs/one.md")) == (
        f"pnk://{partner.kb_id}/{partner.docs['one']}"
    )
    assert str(resolve_target(manifest, "docs/beta.md")) == local.uri("beta")


@pytest.mark.skipif(
    os.geteuid() == 0, reason="root traverses a 0o000 directory, so the state cannot be built"
)
def test_a_document_the_process_cannot_reach_is_refused_with_the_read_error(
    pair: tuple[Kb, Kb],
) -> None:
    """The non-injecting half of `test_an_unreadable_directory_is_refused_rather_than_crashing`.

    That test monkeypatches `Path.is_file` to raise, so the `except OSError` clause is entered on
    both interpreters and it passes on both — while the *real* `Path.is_file()` on 3.14 raises for
    neither errno its own comment names, leaving the production branch dead and the test green on
    top of it. A fake that raises unconditionally cannot tell you whether the real call still
    raises, so it is kept as the unit-level pin of the clause and this is built from a real
    `chmod` beside it: the property under test is which syscall raises on which interpreter, which
    is precisely what injection cannot reach.

    Two shapes, because they are not the same question and only one of them is answered by asking
    about the entry itself. `blocked/inside.md` is refused at its own parent; `alias.md` is an
    entry this process can `lstat` perfectly well whose *target* sits behind that parent.
    """
    local, _partner = pair
    blocked = local.root / "docs" / "blocked"
    blocked.mkdir()
    (blocked / "inside.md").write_text("# Inside\n\ntext\n", encoding="utf-8")
    (local.root / "docs" / "alias.md").symlink_to(blocked / "inside.md")
    os.chmod(blocked, 0o000)
    try:
        with pytest.raises(PinakesError) as direct:
            add(
                load(local.root),
                source="docs/blocked/inside.md",
                target="docs/beta.md",
                rel="cites",
            )
        with pytest.raises(PinakesError) as through_link:
            add(load(local.root), source="docs/alias.md", target="docs/beta.md", rel="cites")
    finally:
        os.chmod(blocked, 0o755)

    assert "cannot be read" in direct.value.message, direct.value.message
    assert "cannot be read" in through_link.value.message, through_link.value.message

    # Two controls, and the first is the one that makes the assertions above mean anything: with
    # the permission restored and nothing else changed, the *same* path stops reporting a read
    # error and moves on to the next check. So "cannot be read" was the block talking, not a
    # symlink or a fixture that was never usable.
    with pytest.raises(PinakesError) as restored:
        add(load(local.root), source="docs/alias.md", target="docs/beta.md", rel="cites")
    assert "has no sidecar" in restored.value.message, restored.value.message

    with pytest.raises(PinakesError) as absent:
        add(load(local.root), source="docs/nowhere.md", target="docs/beta.md", rel="cites")
    assert "is not a document" in absent.value.message, (
        "control: a path that is genuinely absent keeps the message that says so, which is the "
        "distinction the fix exists to restore — refused-to-look is not the same as not-there"
    )
