from typing import Any

class CommentedBase: ...

class CommentedMap(CommentedBase, dict[Any, Any]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class CommentedSeq(CommentedBase, list[Any]):
    def __init__(self, *args: Any) -> None: ...

class TaggedScalar(CommentedBase): ...
